@PORT = 3005

### READ all notes
GET http://localhost:{{PORT}}/notes

### READ a single note
GET http://localhost:{{PORT}}/notes/13

### CREATE a note
POST http://localhost:{{PORT}}/notes
Content-Type: application/json

{
  "content": "play dota2"
}

### UPDATE a note
PUT http://localhost:{{PORT}}/notes/17
Content-Type: application/json

{
  "content": "play even more dota2"
}

### DELETE a note
DELETE http://localhost:{{PORT}}/notes/14